spring:
  application:
    name: product-service
  jpa:
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: ${DDL:create-drop}

  datasource:
    url: jdbc:h2:mem:mydb
    username: test
    password: test
    driverClassName: org.h2.Driver

  h2:
    console.enabled: true

logging:
  level:
    com.netflix.discovery: 'OFF'
    org.springframework.cloud: 'OFF'

springdoc:
  swagger-ui:
    defaultModelsExpandDepth: -1

server:
  port: 8082

discovery:
  eureka-hostname: http://eureka:eureka@localhost:8761/eureka
  client-hostname: product-service

eureka:
  instance:
    hostname: ${discovery.client-hostname}
    prefer-ip-address: true
    instance-id: ${eureka.instance.hostname}:${server.port}
    leaseRenewalIntervalInSeconds: 10
  client:
    register-with-eureka: true
    fetch-registry: true
    registryFetchIntervalSeconds: 5
    service-url:
      defaultZone: ${discovery.eureka-hostname}